input {
  tcp {
    port => 5000
    codec => json_lines {
      decode_size_limit_bytes => 10485760
    }
  }
}

filter {
  if ![service][name] {
    mutate {
      add_field => { "[service][name]" => "unknown-service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "library-hub-%{[service][name]}-%{+YYYY.MM.dd}"
    data_stream => false
    ilm_enabled => false
    manage_template => true
    template => "/usr/share/logstash/templates/library-hub-template.json"
    template_name => "library-hub"
    template_overwrite => true
    template_api => "composable"
  }
}