spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8082

jwt:
  secret: 11f4faa6ee78d80d114ecb683ab010f1aa16796db7e4c2ec1632f416d8dd10cd