spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
        host: localhost  #redis
        port: 6379
        connect-timeout: 2s
        timeout: 2s

  cache:
    type: redis
    cache-names: books

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

jwt:
  secret: 11f4faa6ee78d80d114ecb683ab010f1aa16796db7e4c2ec1632f416d8dd10cd

logging:
  level:
    org.example.bookservice: info